spring:
  kafka:
    consumer:
      #      PROD
      #      bootstrap-servers: 34.86.214.6:9092
      #      DEV
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      #      PROD
      #      bootstrap-servers: 34.86.214.6:9092
      #      DEV
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer